services:
  redis:
    image: "redis:7.4.2-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    image: "ghcr.io/abhiroopks/commute-sense:latest"
    ports:
      - "8000:8000"
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file: "dev.env"
    depends_on:
      - redis
volumes:
  redis_data:
