name: CI

on: [push, pull_request]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Ruff
        run: ruff check .
      
      - name: Test with pytest
        run: |
          cd tests
          pytest --durations=0 -vv test.py

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker image
        run: docker build -t ghcr.io/abhiroopks/commute-sense:latest .

      - name: Push Docker image
        run: docker push ghcr.io/abhiroopks/commute-sense:latest


