name: Deploy App Image to GHCR

on:
  push:
    branches: ["main"]


jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker image
        run: docker build -t ghcr.io/abhiroopks/commute-sense:latest .

      - name: Push Docker image
        run: docker push ghcr.io/abhiroopks/commute-sense:latest
      